[project]
authors = ["stijn", "benny", "andres"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Basalt is a stand-alone machine learning framework that leverages the power of Mojo."
name = "Basalt"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
test = { cmd = "magic run mojo test -I . tests" }
test_mojo = { cmd = "magic run mojo test -I . tests/mojo" }
test_python = { cmd = "magic run mojo test -I . tests/python" }

[dependencies]
max = ">=24.6.0,<25"

[pypi-dependencies]
torch = ">=2.5.1, <3"
torchvision = ">=0.20.1, <0.21"
torchaudio = ">=2.5.1, <3"
